/**
 * Generates the Worker secrets (MASTER_KEY, PW_PEPPER) and the SQL that seeds
 * the single user account. Re-running keeps existing secrets so the stored
 * password hash stays valid.
 *
 *   node scripts/bootstrap.mjs "<email>" "<initial password>"
 */
import { webcrypto as crypto } from 'node:crypto';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const secretsPath = join(root, '.secrets.local.json');
const seedPath = join(root, 'migrations', '9999_seed_user.sql');

const email = String(process.argv[2] || '').trim().toLowerCase();
const password = process.argv[3] || '';
if (!email || !password) {
  console.error('使い方: node scripts/bootstrap.mjs <メールアドレス> <パスワード>');
  process.exit(1);
}

const te = new TextEncoder();
const b64 = (bytes) => Buffer.from(bytes).toString('base64');
const b64url = (bytes) => b64(bytes).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
const rand = (n) => crypto.getRandomValues(new Uint8Array(n));

let secrets = {};
if (existsSync(secretsPath)) {
  secrets = JSON.parse(readFileSync(secretsPath, 'utf8'));
  console.log('既存の .secrets.local.json を再利用します');
}
secrets.MASTER_KEY ||= b64(rand(32));
secrets.PW_PEPPER ||= b64url(rand(32));

const PW_ALGO = 'pbkdf2c-v1';
const PW_ITER = 600000;

async function hmac(secret, msg) {
  const key = await crypto.subtle.importKey('raw', te.encode(secret), { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']);
  return new Uint8Array(await crypto.subtle.sign('HMAC', key, te.encode(msg)));
}

async function clientHash(pw, salt, iterations) {
  const key = await crypto.subtle.importKey('raw', te.encode(pw), 'PBKDF2', false, ['deriveBits']);
  const bits = await crypto.subtle.deriveBits({ name: 'PBKDF2', salt: te.encode(salt), iterations, hash: 'SHA-256' }, key, 256);
  return b64(new Uint8Array(bits));
}

const salt = secrets.PW_SALT || b64url(rand(16));
secrets.PW_SALT = salt;

const ch = await clientHash(password, salt, PW_ITER);
const pwHash = b64(await hmac(secrets.PW_PEPPER, `${PW_ALGO}:${salt}:${ch}`));

const userId = 'usr_' + b64url(rand(12));
const now = Math.floor(Date.now() / 1000);
const sql = `-- generated by scripts/bootstrap.mjs (do not commit)
INSERT INTO users (id, email, pw_hash, pw_salt, pw_algo, pw_iter, totp_enabled, failed_attempts, is_admin, created_at, updated_at)
VALUES ('${userId}', '${email}', '${pwHash}', '${salt}', '${PW_ALGO}', ${PW_ITER}, 0, 0, 1, ${now}, ${now})
ON CONFLICT(email) DO UPDATE SET
  pw_hash = excluded.pw_hash,
  pw_salt = excluded.pw_salt,
  pw_algo = excluded.pw_algo,
  pw_iter = excluded.pw_iter,
  failed_attempts = 0,
  locked_at = NULL,
  updated_at = excluded.updated_at;
`;

writeFileSync(secretsPath, JSON.stringify(secrets, null, 2));
writeFileSync(seedPath, sql);

console.log('');
console.log('  email       :', email);
console.log('  password    :', password.replace(/./g, '*') + ' (' + password.length + ' 文字)');
console.log('  pw_salt     :', salt);
console.log('  secrets file:', secretsPath);
console.log('  seed sql    :', seedPath);
console.log('');
console.log('次のコマンドでシークレットを登録してください:');
console.log('  echo "$MASTER_KEY" | npx wrangler secret put MASTER_KEY');
console.log('  echo "$PW_PEPPER"  | npx wrangler secret put PW_PEPPER');
